import {
  bigint,
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import {
  colorModeEnum,
  duplexModeEnum,
  orientationEnum,
  pageOrderEnum,
  paperSizeEnum,
  paymentStatusEnum,
  printJobStatusEnum,
} from "./enums";
import { kiosks } from "./kiosks";
import { savedFiles } from "./saved-files";

export const printJobs = pgTable(
  "print_jobs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    jobNumber: varchar("job_number", { length: 32 }).notNull().unique(),
    userId: text("user_id").notNull(),
    kioskId: uuid("kiosk_id").references(() => kiosks.id),
    savedFileId: uuid("saved_file_id").references(() => savedFiles.id),
    status: printJobStatusEnum("status").notNull(),
    paymentStatus: paymentStatusEnum("payment_status").notNull(),
    originalFilename: varchar("original_filename", { length: 512 }).notNull(),
    storageKey: varchar("storage_key", { length: 1024 }).notNull(),
    fileSizeBytes: bigint("file_size_bytes", { mode: "number" }).notNull(),
    fileHash: varchar("file_hash", { length: 128 }).notNull(),
    pageCount: integer("page_count").notNull(),
    copies: integer("copies").notNull(),
    pageRange: varchar("page_range", { length: 128 }).notNull(),
    colorMode: colorModeEnum("color_mode").notNull(),
    paperSize: paperSizeEnum("paper_size").notNull(),
    duplex: duplexModeEnum("duplex").notNull(),
    pagesPerSheet: integer("pages_per_sheet").notNull(),
    order: pageOrderEnum("order").notNull(),
    orientation: orientationEnum("orientation").notNull(),
    fitToPage: boolean("fit_to_page").notNull(),
    physicalSheets: integer("physical_sheets"),
    amountPaise: integer("amount_paise"),
    currency: varchar("currency", { length: 8 }).notNull(),
    pricingSnapshot: jsonb("pricing_snapshot"),
    saveFile: boolean("save_file").notNull(),
    fileRetentionUntil: timestamp("file_retention_until", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    paidAt: timestamp("paid_at", { withTimezone: true }),
    claimedAt: timestamp("claimed_at", { withTimezone: true }),
    printingStartedAt: timestamp("printing_started_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    failedAt: timestamp("failed_at", { withTimezone: true }),
  },
  (t) => [
    index("ix_print_jobs_user_id").on(t.userId),
    index("ix_print_jobs_status").on(t.status),
    index("ix_print_jobs_created_at").on(t.createdAt),
    index("ix_print_jobs_kiosk_id").on(t.kioskId),
    index("ix_print_jobs_saved_file_id").on(t.savedFileId),
  ]
);
